import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam
				voluptate rem pariatur aliquid, expedita sed, consequuntur natus labore
				tempora fugit itaque ad dolor maxime, qui sequi. Nobis minus soluta
				culpa?
			</main>
		</div>
	);
}
